### ISSUE TITLE
Can't submit orders in Pure game

### ISSUE THREAD

**Issue by tttppp** [zond/android-diplicity#46]
The map does not have the right highlighting for selectable regions, nor can you create orders.

**Comment by zond** [comment]
Ouch, maybe disable it until that is fixed?

**Comment by tttppp** [comment]
Yep, sounds good. The web UI has a worse bug because it uses its own custom map. Just about to raise that.

I bet the autogenerated REST UI works fine though!

**Comment by zond** [comment]
Ah yeah, the dipl.io site probably breaks for the new maps.

Haha yup, the autogenerated stuff should work, but it's generous to call it
a UI..

On May 24, 2017 19:51, "tttppp" <notifications@github.com> wrote:

Yep, sounds good. The web UI has a worse bug because it uses its own custom
map. Just about to raise that.

I bet the autogenerated REST UI works fine though!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/zond/android-diplicity/issues/46#issuecomment-303801008>,
or mute the thread

**Comment by tttppp** [comment]
The auto-generated site works, and I can even see my order through the app!  Not brilliant though.  Hopefully this is something either wrong with the svg, or the app has some reference to the original map hardcoded somehow (e.g. territory ids or dimensions).  I'll have a quick look now to see if I can spot what.

**Comment by zond** [comment]
Probably the SVG lacks something... Don't remember what that would be tough
:/

On May 24, 2017 20:15, "tttppp" <notifications@github.com> wrote:

The auto-generated site works, and I can even see my order through the app!
Not brilliant though. Hopefully this is something either wrong with the
svg, or the app has some reference to the original map hardcoded somehow
(e.g. territory ids or dimensions). I'll have a quick look now to see if I
can spot what.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/zond/android-diplicity/issues/46#issuecomment-303807739>,
or mute the thread
