### ISSUE TITLE
$game_name needs orders message even though RDY was already checked

### ISSUE THREAD

**Issue by GijsTimmers** [zond/android-diplicity#59]
Sometimes, I get this warning. I'm not sure why; perhaps the `RDY` button is pressed while being offline? Is there any feedback in the app to make sure that the `RDY` press is actually processed by the server?

**Comment by zond** [comment]
The warning is totally controlled by the client. What happens is that every
time a game is loaded, it automatically updates the alarm for that game.

If you are a member of the game, the game is ongoing, and you are expected
to give orders, it creates or modifies the alarm. Otherwise it deletes it.

When the alarm goes off, it tries to load the game, to see if you re still
expected to give orders. If you are, it shows the notification, otherwise
it doesn't.

If it can't load the game it will, IIRC, show the notification for good
measure.

But, I think there is a bug: When you click RDY, it doesn't reload the
game. So if you exit the app, it won't have updated the alarm.

To fix this,
https://github.com/zond/android-diplicity/blob/master/app/src/main/java/se/oort/diplicity/MemberTable.java#L146
needs to do what
https://github.com/zond/android-diplicity/blob/5536c3c1c61f78fcd241b18b5b9a201b2b3a9ac7/app/src/main/java/se/oort/diplicity/GameUnserializer.java#L59
and
https://github.com/zond/android-diplicity/blob/5536c3c1c61f78fcd241b18b5b9a201b2b3a9ac7/app/src/main/java/se/oort/diplicity/GameUnserializer.java#L62
does.


On Aug 6, 2017 10:38, "GijsTimmers" <notifications@github.com> wrote:

Sometimes, I get this warning. I'm not sure why; perhaps the RDY button is
pressed while being offline? Is there any feedback in the app to make sure
that the RDY press is actually processed by the server?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zond/android-diplicity/issues/59>, or mute the thread

**Comment by GijsTimmers** [comment]
Right. I will see if I can find out more precisely what triggers this bug.
